[package]
name = "starpoints"
version = "0.1.0"
description = "Starpoints Solana Program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "starpoints"

[features]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.31.1"
anchor-spl = { version = "0.31.1", features = ["token"] }

[dev-dependencies]